apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-nrf-config
  labels:
    epc-mode: nrf
data:
  nrf.yaml: |
    logger:
        file: /var/log/open5gs/nrf.log

    sbi:
        server:
          no_tls: true
          cacert: /etc/open5gs/tls/ca.crt
          key: /etc/open5gs/tls/nrf.key
          cert: /etc/open5gs/tls/nrf.crt
        client:
          no_tls: true
          cacert: /etc/open5gs/tls/ca.crt
          key: /etc/open5gs/tls/nrf.key
          cert: /etc/open5gs/tls/nrf.crt
    nrf:
        sbi:
          addr: 0.0.0.0
