apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-pcf-config
  labels:
    epc-mode: pcf
data:
  pcf.yaml: |
    logger:
        file: /var/log/open5gs/pcf.log
    sbi:
        server:
          no_tls: true
          cacert: /etc/open5gs/tls/ca.crt
          key: /etc/open5gs/tls/pcf.key
          cert: /etc/open5gs/tls/pcf.crt
        client:
          no_tls: true
          cacert: /etc/open5gs/tls/ca.crt
          key: /etc/open5gs/tls/pcf.key
          cert: /etc/open5gs/tls/pcf.crt
    
    db_uri: mongodb://{{ .Release.Name }}-mongodb-svc/open5gs    

    pcf:
      sbi:     
      - addr: 0.0.0.0
        advertise: {{ .Release.Name }}-pcf
    nrf:
     sbi:
      name: {{ .Release.Name }}-nrf
