apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-smf-config
  labels:
    epc-mode: smf
data:
  smf.yaml: |
    logger:
        file: /var/log/open5gs/smf.log
    sbi:
        server:
          no_tls: true
          cacert: /etc/open5gs/tls/ca.crt
          key: /etc/open5gs/tls/nrf.key
          cert: /etc/open5gs/tls/nrf.crt
        client:
          no_tls: true
          cacert: /etc/open5gs/tls/ca.crt
          key: /etc/open5gs/tls/nrf.key
          cert: /etc/open5gs/tls/nrf.crt

    parameter:
        no_ipv6: true

    smf:
        sbi:     
        - addr: 0.0.0.0
          advertise: {{ .Release.Name }}-smf
        pfcp:
           dev: {{ .Values.k8s.interface }}
        gtpc:
          dev: {{ .Values.k8s.interface }}
        gtpu:
          dev: {{ .Values.k8s.interface }}    
        subnet:
         - addr: 10.45.0.1/16
           dnn: {{ .Values.dnn }}
        dns:
          - 8.8.8.8
          - 8.8.4.4
        mtu: 1400

    nrf:
     sbi:
      name: {{ .Release.Name }}-nrf 

    upf:
      pfcp:
        - name: {{ .Release.Name }}-upf-svc
          dnn: {{ .Values.dnn }}
