apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-udm-config
  labels:
    epc-mode: udm
data:
  udm.yaml: |
    logger:
        file: /var/log/open5gs/udm.log

    sbi:
        server:
          no_tls: true
          cacert: /etc/open5gs/tls/ca.crt
          key: /etc/open5gs/tls/udm.key
          cert: /etc/open5gs/tls/udm.crt
        client:
          no_tls: true
          cacert: /etc/open5gs/tls/ca.crt
          key: /etc/open5gs/tls/udm.key
          cert: /etc/open5gs/tls/udm.crt

    udm:
      sbi:   
      - addr: 0.0.0.0
        advertise: {{ .Release.Name }}-udm
    nrf:
     sbi:
      name: {{ .Release.Name }}-nrf
