apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-upf-config
  labels:
    epc-mode: upf
data:
  upf.yaml: |
    logger:
        file: /var/log/open5gs/upf.log

        sbi:
    server:
      no_tls: true
      cacert: /etc/open5gs/tls/ca.crt
      key: /etc/open5gs/tls/upf.key
      cert: /etc/open5gs/tls/upf.crt
    client:
      no_tls: true
      cacert: /etc/open5gs/tls/ca.crt
      key: /etc/open5gs/tls/upf.key
      cert: /etc/open5gs/tls/upf.crt



    upf:
        pfcp:
           dev: {{ .Values.k8s.interface }}
        gtpu:
           dev: {{ .Values.k8s.interface }}
        subnet:
          - addr: 10.45.0.1/16
            dnn: {{ .Values.dnn }}
